import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Knex } from 'knex'
import { knex } from '@/config/knex'
import Stopwatch from '@/components/Stopwatch'

const inter = Inter({ subsets: ['latin'] })

function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Stopwatch />

        <ul>
          {data.map((entry: any) => <li key={entry.id}>{Object.entries(entry).toString()}</li>)}
        </ul>
        {/* {Object.entries(data).toString()} */}

        <form action="/api/hello" method="post">
          <label htmlFor="name">Name:</label>
          <input type="text" id="name" name="name" required />
          <label htmlFor="score">Score:</label>
          <input type="number" id="score" name="score" required />
          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  // knex.schema.dropTableIfExists('runs')
  if (!await knex.schema.hasTable('runs')) {
    await knex.schema.createTable('runs', (t: Knex.TableBuilder) => {
      t.increments('id').primary();
      t.string('name', 100);
      t.integer('score');
      t.timestamp('submitted_at');
    });
  }

  const data = await knex('runs').select();
  // console.log(data);

  return { props: { data } }
}

export default Home